React query
TheManaTech/BrokerPlatformFrontEnd pull request #21
Opened 2021-11-30 22:19 UTC by niksfred

I have implemented useQuery to fetch Clients, Notes, RealEstates and Notes inside the PropertyPage. Fetching for information inside the PropertyPage needs to be implemented, but I had troubles today with the data formatting.

2021-12-01 22:15 UTC, Galabov93 requested changes
Nice work!!! The code quality has upped a notch.

2021-12-01 22:15 UTC, Galabov93 commented on src/api/realEstates/index.js
> +export const fetchRealEstatesData = async ({ LIMIT, props }) => {
LIMIT can be imported as a constant, not through arguments.

2021-12-01 22:15 UTC, Galabov93 commented on src/api/realEstates/index.js
> +export const fetchRealEstatesData = async ({ LIMIT, props }) => {
Also, please pass the data in a more verbose way. Instead of passing "props", pass page, currentFilters

2021-12-01 22:15 UTC, Galabov93 commented on src/api/realEstates/index.js
> +export const fetchRealEstateDataById = async ({ match }) => {
Same as above.

2021-12-01 22:15 UTC, Galabov93 commented on src/components/ClientsTable/index.js
> +  console.log(tableData);
remove

2021-12-01 22:15 UTC, Galabov93 commented on src/pages/PropertyPage/index.js
> +  const { data: realEstatesData, isLoading } = useQuery(
Very nice change. 👍

2021-12-01 22:15 UTC, Galabov93 commented on src/pages/PropertyPage/index.js
> +    !isLoading && (
Please remove this line and add above:
`if(isLoading) return <FullScreenLoader />`

2021-12-01 22:15 UTC, Galabov93 commented on src/pages/RealEstates/index.js
> +// import { animateScroll as scroll } from "react-scroll";
Is this replaced in any way? Why is it just removed?

2021-12-01 22:15 UTC, Galabov93 commented on src/pages/RealEstates/index.js
> +        {!isLoading && realEstatesData.length ? (
This can be removed

2021-12-01 22:15 UTC, Galabov93 commented on src/pages/RealEstates/index.js
> +  if (isLoading) return null;
Add the loader here/

2021-12-02 15:15 UTC, niksfred commented on src/api/realEstates/index.js
> +export const fetchRealEstatesData = async ({ LIMIT, props }) => {
LIMIT exported at top level in the RealEstates file and then imported in the API one.

2021-12-02 15:39 UTC, niksfred commented on src/api/realEstates/index.js
> +export const fetchRealEstatesData = async ({ LIMIT, props }) => {
props changed with currentFilters and page using nested destructuring.

2021-12-02 15:51 UTC, niksfred commented on src/pages/RealEstates/index.js
> +  if (isLoading) return null;
Added.

2021-12-02 16:12 UTC, niksfred commented on src/pages/RealEstates/index.js
> +// import { animateScroll as scroll } from "react-scroll";
Commented outside and resolved with you.

2021-12-02 23:15 UTC, merged