Add clients creator
TheManaTech/BrokerPlatformFrontEnd pull request #23
Opened 2021-12-15 18:45 UTC by niksfred

Ivan's userId (3) hardcoded to have access to all users emails when assigning clients

2021-12-15 21:40 UTC, Galabov93 requested changes
@niksfred Nice work. The functionality is working.
There is a need to tweak the functionality a bit so it is more user-friendly.

2021-12-15 21:40 UTC, Galabov93 commented on src/components/AddClient/index.js
> +    const newClientData = mapValues(values);
Please revert the old functionality for non-Ivan emails, meaning:
The Broker dropdown should be visible only for Ivan(and Dani) actually and the rest should not be seeing the dropdown, but instead automatically assign their userID.

2021-12-15 21:40 UTC, Galabov93 commented on src/components/AddClient/index.js
> +                userId: "",
You could create a function for getting the usedId. 
```suggestion
                userId: getAdminUserId(),
```

2021-12-15 21:40 UTC, Galabov93 commented on src/components/AddClient/index.js
> +                  <FormMultipleSelect
Create a bool value that shows if the user is admin or not and show the dropdown based on it
```suggestion
                  {isAdminUser && <FormMultipleSelect
```

2021-12-16 13:25 UTC, niksfred commented
Couldn't set directly userID in the initial value for userId, so the situation is handled by mappedValues.

2022-03-30 16:56 UTC, merged