Single project page
TheManaTech/BrokerPlatformFrontEnd pull request #34
Opened 2022-04-07 13:04 UTC by niksfred

New page for creating project initialized. Responsive styles added. Need functionality for editing project.

2022-04-07 13:14 UTC, Galabov93 commented on src/components/SingleProjectPage/index.jsx
> +    margin: "12px 0px"
theme.spacing

2022-04-07 13:14 UTC, Galabov93 commented on src/components/SingleProjectPage/index.jsx
> +    margin: "12px 0px"
Same as above

2022-04-07 13:14 UTC, Galabov93 commented on src/components/SingleProjectPage/index.jsx
> +                sx={{ backgroundColor: "red" }}
Use className and theme colors here

2022-04-07 13:14 UTC, Galabov93 commented on src/pages/Projects/index.jsx
> +    paddingLeft: "0.25rem",
theme.spacing

2022-04-07 13:14 UTC, Galabov93 commented on src/pages/Projects/index.jsx
> +      paddingTop: "2rem",
theme.spacing

2022-04-11 15:50 UTC, Galabov93 requested changes
Well done! @niksfred 
There are a few things left to do;
- Fix the small comments listed here.
- Add a button on the table that redirrects you to the edit page
- Remove the edit in the route, so it only `projects/:id`

2022-04-11 15:50 UTC, Galabov93 commented on src/components/SingleProjectPage/helpers.js
> +  return editMode
You can declare on a new object `dataObj` with all data except id. And add the statement
`if(editMode) return {...dateObj, id:values.id`
`else return dateObj.`
This would save us some lines of code and it would be more clear to see the difference.

2022-04-11 15:50 UTC, Galabov93 commented on src/components/SingleProjectPage/index.jsx
> +    flexDirection: "row",
flexDirection is row by default. This line can be omited.

2022-04-11 15:50 UTC, Galabov93 commented on src/pages/Projects/index.jsx
> +    paddingLeft: theme.spacing(1),
```suggestion
    padding: `${theme.spacing(2)} ${theme.spacing(1)` ,
```

2022-04-11 15:50 UTC, Galabov93 commented on src/pages/Projects/index.jsx
> +      paddingTop: theme.spacing(4),
Same as above

2022-04-11 15:50 UTC, Galabov93 commented on src/pages/Projects/index.jsx
> +  console.log(tableData)
Remove log

2022-04-11 19:33 UTC, niksfred commented on src/components/SingleProjectPage/helpers.js
> +  return editMode
Thanks about that. I knew there was a smarter way of doing this just for one.

2022-04-12 21:34 UTC, Galabov93 commented
@niksfred All seems to start looking pretty good now.
Please rename "Edit" and "Delete" column to their Bulgarian alternative, across datatable pages 😄

2022-04-13 14:08 UTC, Galabov93 commented on src/pages/Projects/index.jsx
> +        accessor: (rowData) => rowData["client.name"],
👍

2022-04-13 14:16 UTC, Galabov93 approved these changes
Гут то го

2022-04-13 14:16 UTC, merged